version: "3"
services:
  nginx:
    image: jc21/nginx-proxy-manager:2
    restart: always
    ports:
      # Public HTTP Port:
      - '8090:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    volumes:
      # Make sure this config.json file exists as per instructions above:
      - /share/CACHEDEV1_DATA/nginx/config.json:/app/config/production.json
      - /share/CACHEDEV1_DATA/nginx/data:/data
      - /share/CACHEDEV1_DATA/nginx/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: jc21/mariadb-aria:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - /share/CACHEDEV1_DATA/nginx/data/mysql:/var/lib/mysql
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - BASE_URL=/ombi #optional
    volumes:
      - /share/CACHEDEV1_DATA/ombi/config1080:/config
    ports:
      - 13579:3579
    restart: unless-stopped