version: "3"
services:
  nzbhydra2only:
    image: hotio/nzbhydra2:stable-2.14.2
    container_name: nzbhydra2only
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Detroit
      - ARGS=""
      - DEBUG="no"
    volumes:
      - /share/CACHEDEV1_DATA/nzbhydra2/config:/config
    ports:
      - 12714:5076
    restart: unless-stopped