version: "3"
services:
  radarr1080only:
    image: linuxserver/radarr:3.0.0.2719-ls1
    container_name: radarr1080only
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Detroit
      - UMASK_SET=022 #optional
    volumes:
      - /share/CACHEDEV1_DATA/radarr/config1080:/config
      - /share/CACHEDEV1_DATA/plex/movies1080:/movies
      - /share/CACHEDEV1_DATA/sabnzbd/downloads1080:/downloads
    ports:
      - 12701:7878
    restart: unless-stopped