version: "3"
services:
  sonarr1080only:
    image: linuxserver/sonarr:2.0.0.5344-ls53
    container_name: sonarr1080only
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - UMASK_SET=022 #optional
    volumes:
      - /share/CACHEDEV1_DATA/sonarr/config1080:/config
      - /share/CACHEDEV1_DATA/plex/series1080:/tv
      - /share/CACHEDEV1_DATA/sabnzbd/downloads1080:/downloads
    ports:
      - 12702:8989
    restart: unless-stopped