version: "3"
services:
  # latest versions as of 8/4/2022 
  #   to fix the sabnzbd 403 errors, need to add domain to whitelist in settings
  #
  # ports:
  #  tautulli: 12701
  #  ombi: 12702
  #  radarr4k: 12710
  #  radarr1080: 12711
  #  radarrKids: 12712
  #  sonarr1080: 12720 
  #  sonarrKids: 12721 
  #  sabnzbd4k: 12730, 12731
  #  sabnzbd1080: 12732, 12733
  #  sabnzbdKids: 12734, 12735
  #  nzbhydra2: 12740
  #
  # versions:
  #  radarr: https://hub.docker.com/r/linuxserver/radarr/tags?page=1&ordering=name&name=version
  #  sonarr: https://hub.docker.com/r/linuxserver/sonarr/tags?page=1&ordering=name&name=version
  #  sabnzbd: https://hub.docker.com/r/linuxserver/sabnzbd/tags?page=1&ordering=name&name=version
  #  nzbhydra2: https://hub.docker.com/r/hotio/nzbhydra2/tags?page=1&ordering=last_updated&name=release
  #  tautulli: https://hub.docker.com/r/linuxserver/tautulli/tags?page=1&ordering=name&name=version
  #  ombi: https://hub.docker.com/r/linuxserver/ombi/tags?page=1&ordering=name&name=version
  #
  radarr4k:
    image: linuxserver/radarr:version-4.1.0.6175
    container_name: radarr4k
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Detroit
      - UMASK_SET=022 #optional
    volumes:
      - /share/CACHEDEV1_DATA/radarr/config4k:/config
      - /share/CACHEDEV1_DATA/plex/movies4k:/movies
      - /share/CACHEDEV1_DATA/sabnzbd/downloads4k:/downloads
    ports:
      - 12710:7878
    depends_on:
      - sabnzbd4k
      - nzbhydra2
    restart: unless-stopped
  radarr1080:
    image: linuxserver/radarr:version-4.1.0.6175
    container_name: radarr1080
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Detroit
      - UMASK_SET=022 #optional
    volumes:
      - /share/CACHEDEV1_DATA/radarr/config1080:/config
      - /share/CACHEDEV1_DATA/plex/movies1080:/movies
      - /share/CACHEDEV1_DATA/sabnzbd/downloads1080:/downloads
    ports:
      - 12711:7878
    depends_on:
      - sabnzbd1080
      - nzbhydra2
    restart: unless-stopped
  radarrKids:
    image: linuxserver/radarr:version-4.1.0.6175
    container_name: radarrKids
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Detroit
      - UMASK_SET=022 #optional
    volumes:
      - /share/CACHEDEV1_DATA/radarr/configKids:/config
      - /share/CACHEDEV1_DATA/plex/moviesKids:/movies
      - /share/CACHEDEV1_DATA/sabnzbd/downloadsKids:/downloads
    ports:
      - 12712:7878
    depends_on:
      - sabnzbdKids
      - nzbhydra2
    restart: unless-stopped
  sonarr1080:
    image: linuxserver/sonarr:version-3.0.8.1507
    container_name: sonarr1080
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Detroit
      - UMASK_SET=022 #optional
    volumes:
      - /share/CACHEDEV1_DATA/sonarr/config1080:/config
      - /share/CACHEDEV1_DATA/plex/series1080:/tv
      - /share/CACHEDEV1_DATA/sabnzbd/downloads1080:/downloads
    ports:
      - 12720:8989
    depends_on:
      - sabnzbd1080
      - nzbhydra2
    restart: unless-stopped
  sonarrKids:
    image: linuxserver/sonarr:version-3.0.8.1507
    container_name: sonarrKids
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Detroit
      - UMASK_SET=022 #optional
    volumes:
      - /share/CACHEDEV1_DATA/sonarr/configKids:/config
      - /share/CACHEDEV1_DATA/plex/seriesKids:/tv
      - /share/CACHEDEV1_DATA/sabnzbd/downloadsKids:/downloads
    ports:
      - 12721:8989
    depends_on:
      - sabnzbdKids
      - nzbhydra2
    restart: unless-stopped
  sabnzbd4k:
    image: linuxserver/sabnzbd:version-3.6.0
    container_name: sabnzbd4k
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Detroit
    volumes:
      - /share/CACHEDEV1_DATA/sabnzbd/config4k:/config
      - /share/CACHEDEV1_DATA/sabnzbd/downloads4k:/downloads
      - /share/CACHEDEV1_DATA/sabnzbd/incomplete-downloads4k:/incomplete-downloads #optional
    ports:
      - 12730:8080
      - 12731:9090
    restart: unless-stopped
  sabnzbd1080:
    image: linuxserver/sabnzbd:version-3.6.0
    container_name: sabnzbd1080
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Detroit
    volumes:
      - /share/CACHEDEV1_DATA/sabnzbd/config1080:/config
      - /share/CACHEDEV1_DATA/sabnzbd/downloads1080:/downloads
      - /share/CACHEDEV1_DATA/sabnzbd/incomplete-downloads1080:/incomplete-downloads #optional
    ports:
      - 12732:8080
      - 12733:9090
    restart: unless-stopped
  sabnzbdKids:
    image: linuxserver/sabnzbd:version-3.6.0
    container_name: sabnzbdKids
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Detroit
    volumes:
      - /share/CACHEDEV1_DATA/sabnzbd/configKids:/config
      - /share/CACHEDEV1_DATA/sabnzbd/downloadsKids:/downloads
      - /share/CACHEDEV1_DATA/sabnzbd/incomplete-downloadsKids:/incomplete-downloads #optional
    ports:
      - 12734:8080
      - 12735:9090
    restart: unless-stopped
  nzbhydra2:
    image: hotio/nzbhydra2:release-4.4.0
    container_name: nzbhydra2
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Detroit
      - ARGS=""
      - DEBUG="no"
    volumes:
      - /share/CACHEDEV1_DATA/nzbhydra2/config:/config
    ports:
      - 12740:5076
    restart: unless-stopped
  tautulli:
    image: linuxserver/tautulli:version-v2.9.7
    container_name: tautulli
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Detroit
    volumes:
      - /share/CACHEDEV1_DATA/tautulli/config:/config
      - /share/CACHEDEV1_DATA/tautulli/logs:/logs
    ports:
      - 12701:8181
    restart: unless-stopped
  ombi:
    image: linuxserver/ombi:version-v4.3.3
    container_name: ombi
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Detroit
      - BASE_URL=/ombi #optional
    volumes:
      - /share/CACHEDEV1_DATA/ombi/config:/config
    ports:
      - 12702:3579
    depends_on:
      - sonarr1080
      - radarr1080
    restart: unless-stopped