version: "3"
services:
  # latest versions as of 8/4/2022
  #
  # ports: 
  #  plex: 32400
  #
  # versions:
  #  plex: https://hub.docker.com/r/linuxserver/plex/tags?page=1&ordering=name&name=version
  #
  plex:
    image: linuxserver/plex:version-1.28.0.5999-97678ded3
    container_name: plex
    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - /share/CACHEDEV1_DATA/plex/config:/config
      - /share/CACHEDEV1_DATA/plex/moviesKids:/moviesKids
      - /share/CACHEDEV1_DATA/plex/movies4k:/movies4k
      - /share/CACHEDEV1_DATA/plex/movies1080:/movies1080
      - /share/CACHEDEV1_DATA/plex/series1080:/tv
      - /share/CACHEDEV1_DATA/plex/seriesKids:/tvKids
    # ports:
    #   - 12700:32400
    restart: unless-stopped