version: "3"
services:
  scheduled:
    image: dkhunt27/speedtest-via-wowway-scrape
    container_name: speedtest-via-wowway-scrape
    network_mode: bridge
    environment:
      - SPEEDTEST_INTERVAL_MINUTES=60
    volumes:
      - /share/CACHEDEV1_DATA/speedtest/db:/app/data
  ui:
    image: dkhunt27/speedtest-ui
    container_name: speedtest-ui
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Detroit
      - UMASK_SET=022 #optional
    volumes:
      - /share/CACHEDEV1_DATA/speedtest/db:/config/www/db
    ports:
      - '8088:80'
