version: "3"
services:
  # scheduled:
  #   image: dkhunt27/speedtest-via-wowway-scrape
  #   container_name: speedtest-via-wowway-scrape
  #   network_mode: bridge
  #   environment:
  #     - SPEEDTEST_INTERVAL_MINUTES=60
  #   volumes:
  #     - /share/CACHEDEV1_DATA/speedtest/db:/app/data
  scheduled:
    image: dkhunt27/speedtest-via-speed-test
    container_name: speedtest-via-speed-test
    network_mode: bridge
    environment:
      - SPEEDTEST_INTERVAL_MINUTES=60
    volumes:
      - /share/CACHEDEV1_DATA/speedtest/db:/app/data
    restart: unless-stopped
  ui:
    image: dkhunt27/speedtest-ui:v1
    container_name: speedtest-ui
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Detroit
      - UMASK_SET=022 #optional
    volumes:
      - /share/CACHEDEV1_DATA/speedtest/db:/config/www/db
    ports:
      - '8088:80'
    restart: unless-stopped
  openspeedtest: 
    image: openspeedtest/latest
    container_name: openspeedtest
    ports:
      - '8086:3000'
      - '8087:3001'
    restart: unless-stopped

