version: "3"
services:
  radarr4k:
    image: roest/docker-speedtest-analyser
    container_name: speedtest
    network_mode: bridge
    volumes:
      - /share/CACHEDEV1_DATA/speedtest:/var/www/html/data
    ports:
      - 8081:80
      - 4343:443
    environment:
      - CRONJOB_ITERATION=15